version: "3.7"

x-env: &env
  NAME: "balanced"
  NETWORK_NAME: "mainnet"

services:
  balanced-api:
    build:
      context: ${BALANCED_CONTEXT:-.}
      target: ${BALANCED_TARGET:-prod}
      args:
        - SERVICE_NAME=api
    ports:
      - "8000:8000"     # API
      - "8180:8180"     # Health
      - "9400:9400"     # Prometheus
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${BALANCED_CONTEXT:-.}/balanced_backend:/app
    environment:
      <<: *env

  balanced-worker:
    build:
      context: ${BALANCED_CONTEXT:-.}
      target: ${BALANCED_TARGET:-prod}
      args:
        - SERVICE_NAME=worker
    command:
      - worker
      - head
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${BALANCED_CONTEXT:-.}/balanced_backend:/app
    environment:
      <<: *env

  balanced-cron:
    build:
      context: ${BALANCED_CONTEXT:-.}
      target: ${BALANCED_TARGET:-prod}
      args:
        - SERVICE_NAME=worker
    command:
      - worker
      - cron

    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${BALANCED_CONTEXT:-.}/balanced_backend:/app
    environment:
      <<: *env
