"""v0.1.0-add-token-liquidity

Revision ID: 0de2c7d78956
Revises: 98ee638ebbf7
Create Date: 2023-03-06 20:20:28.004516

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0de2c7d78956'
down_revision = '98ee638ebbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('liquidity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'liquidity')
    # ### end Alembic commands ###
