"""init

Revision ID: 134216866d62
Revises: 
Create Date: 2022-06-20 05:00:18.204096

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '134216866d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_historical',
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('update_interval', sa.Integer(), nullable=True),
    sa.Column('days_since_launch', sa.Integer(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contract_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'address', 'method')
    )
    op.create_index(op.f('ix_daily_historical_contract_name'), 'daily_historical', ['contract_name'], unique=False)
    op.create_index(op.f('ix_daily_historical_days_since_launch'), 'daily_historical', ['days_since_launch'], unique=False)
    op.create_index(op.f('ix_daily_historical_update_interval'), 'daily_historical', ['update_interval'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_historical_update_interval'), table_name='daily_historical')
    op.drop_index(op.f('ix_daily_historical_days_since_launch'), table_name='daily_historical')
    op.drop_index(op.f('ix_daily_historical_contract_name'), table_name='daily_historical')
    op.drop_table('daily_historical')
    # ### end Alembic commands ###
