"""v0.1.0-add-dex-adds

Revision ID: 16e92be12b8f
Revises: 80f136ddaec4
Create Date: 2023-02-24 17:43:58.088212

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16e92be12b8f'
down_revision = '80f136ddaec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dex_adds',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('transaction_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_decimal', sa.Float(), nullable=True),
    sa.Column('base', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_decimal', sa.Float(), nullable=True),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_decimal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'transaction_hash', 'log_index')
    )
    op.create_index(op.f('ix_dex_adds_block_number'), 'dex_adds', ['block_number'], unique=False)
    op.create_index(op.f('ix_dex_adds_timestamp'), 'dex_adds', ['timestamp'], unique=False)
    op.drop_index('ix_token_prices_chain_id', table_name='token_prices')
    op.drop_table('token_prices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_prices',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_supply', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', 'timestamp', name='token_prices_pkey')
    )
    op.create_index('ix_token_prices_chain_id', 'token_prices', ['chain_id'], unique=False)
    op.drop_index(op.f('ix_dex_adds_timestamp'), table_name='dex_adds')
    op.drop_index(op.f('ix_dex_adds_block_number'), table_name='dex_adds')
    op.drop_table('dex_adds')
    # ### end Alembic commands ###
