"""init

Revision ID: 1733b8468514
Revises: 
Create Date: 2022-06-05 01:02:18.495741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1733b8468514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans_chart',
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_loans_chart_timestamp'), 'loans_chart', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_chart_timestamp'), table_name='loans_chart')
    op.drop_table('loans_chart')
    # ### end Alembic commands ###
