"""init

Revision ID: 5871b99d98bf
Revises: 
Create Date: 2022-06-20 19:37:22.753950

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5871b99d98bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_historicals',
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('update_interval', sa.Integer(), nullable=True),
    sa.Column('days_since_launch', sa.Integer(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contract_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'address', 'method')
    )
    op.create_index(op.f('ix_daily_historicals_address'), 'daily_historicals', ['address'], unique=False)
    op.create_index(op.f('ix_daily_historicals_contract_name'), 'daily_historicals', ['contract_name'], unique=False)
    op.create_index(op.f('ix_daily_historicals_days_since_launch'), 'daily_historicals', ['days_since_launch'], unique=False)
    op.create_index(op.f('ix_daily_historicals_method'), 'daily_historicals', ['method'], unique=False)
    op.create_index(op.f('ix_daily_historicals_timestamp'), 'daily_historicals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_daily_historicals_update_interval'), 'daily_historicals', ['update_interval'], unique=False)
    op.create_index(op.f('ix_daily_historicals_value'), 'daily_historicals', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_historicals_value'), table_name='daily_historicals')
    op.drop_index(op.f('ix_daily_historicals_update_interval'), table_name='daily_historicals')
    op.drop_index(op.f('ix_daily_historicals_timestamp'), table_name='daily_historicals')
    op.drop_index(op.f('ix_daily_historicals_method'), table_name='daily_historicals')
    op.drop_index(op.f('ix_daily_historicals_days_since_launch'), table_name='daily_historicals')
    op.drop_index(op.f('ix_daily_historicals_contract_name'), table_name='daily_historicals')
    op.drop_index(op.f('ix_daily_historicals_address'), table_name='daily_historicals')
    op.drop_table('daily_historicals')
    # ### end Alembic commands ###
