"""v0.7.1 add head to series

Revision ID: 588a77c865e3
Revises: 026c4de9d667
Create Date: 2024-10-27 14:30:33.557685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '588a77c865e3'
down_revision = '026c4de9d667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contract_method_volumes_end_date'), 'contract_method_volumes', ['end_date'], unique=False)
    op.create_index(op.f('ix_contract_method_volumes_start_date'), 'contract_method_volumes', ['start_date'], unique=False)
    op.add_column('pool_series_15_min', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('pool_series_1_day', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('pool_series_1_hour', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('pool_series_1_month', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('pool_series_1_week', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('pool_series_4_hour', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('pool_series_5_min', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('token_series_15_min', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('token_series_1_day', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('token_series_1_hour', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('token_series_1_month', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('token_series_1_week', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('token_series_4_hour', sa.Column('head', sa.Boolean(), nullable=True))
    op.add_column('token_series_5_min', sa.Column('head', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_series_5_min', 'head')
    op.drop_column('token_series_4_hour', 'head')
    op.drop_column('token_series_1_week', 'head')
    op.drop_column('token_series_1_month', 'head')
    op.drop_column('token_series_1_hour', 'head')
    op.drop_column('token_series_1_day', 'head')
    op.drop_column('token_series_15_min', 'head')
    op.drop_column('pool_series_5_min', 'head')
    op.drop_column('pool_series_4_hour', 'head')
    op.drop_column('pool_series_1_week', 'head')
    op.drop_column('pool_series_1_month', 'head')
    op.drop_column('pool_series_1_hour', 'head')
    op.drop_column('pool_series_1_day', 'head')
    op.drop_column('pool_series_15_min', 'head')
    op.drop_index(op.f('ix_contract_method_volumes_start_date'), table_name='contract_method_volumes')
    op.drop_index(op.f('ix_contract_method_volumes_end_date'), table_name='contract_method_volumes')
    # ### end Alembic commands ###
