"""add tokens, token_prices, and pool_participants tables

Revision ID: 66dff7210728
Revises: e812ecf96b8e
Create Date: 2023-01-26 04:16:31.049652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '66dff7210728'
down_revision = 'e812ecf96b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_participants',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_amount', sa.Float(), nullable=True),
    sa.Column('quote_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_pool_participants_pool_id'), 'pool_participants', ['pool_id'], unique=False)
    op.create_table('pool_prices',
    sa.Column('base_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('price', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('base_address', 'quote_address', 'timestamp')
    )
    op.create_index(op.f('ix_pool_prices_pool_id'), 'pool_prices', ['pool_id'], unique=False)
    op.create_table('pools',
    sa.Column('base_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_decimals', sa.Integer(), nullable=True),
    sa.Column('quote_decimals', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_7d', sa.Float(), nullable=True),
    sa.Column('price_change_30d', sa.Float(), nullable=True),
    sa.Column('holders', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('base_address', 'quote_address')
    )
    op.create_index(op.f('ix_pools_base_address'), 'pools', ['base_address'], unique=False)
    op.create_index(op.f('ix_pools_chain_id'), 'pools', ['chain_id'], unique=False)
    op.create_index(op.f('ix_pools_pool_id'), 'pools', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pools_quote_address'), 'pools', ['quote_address'], unique=False)
    op.create_table('token_prices',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_table('tokens',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('logo_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_24h', sa.Float(), nullable=True),
    sa.Column('price_7d', sa.Float(), nullable=True),
    sa.Column('price_30d', sa.Float(), nullable=True),
    sa.Column('holders', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'chain_id')
    )
    op.create_index(op.f('ix_tokens_address'), 'tokens', ['address'], unique=False)
    op.create_index(op.f('ix_tokens_chain_id'), 'tokens', ['chain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_chain_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_address'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('token_prices')
    op.drop_index(op.f('ix_pools_quote_address'), table_name='pools')
    op.drop_index(op.f('ix_pools_pool_id'), table_name='pools')
    op.drop_index(op.f('ix_pools_chain_id'), table_name='pools')
    op.drop_index(op.f('ix_pools_base_address'), table_name='pools')
    op.drop_table('pools')
    op.drop_index(op.f('ix_pool_prices_pool_id'), table_name='pool_prices')
    op.drop_table('pool_prices')
    op.drop_index(op.f('ix_pool_participants_pool_id'), table_name='pool_participants')
    op.drop_table('pool_participants')
    # ### end Alembic commands ###
