"""v0.1.0-add-token-fields

Revision ID: a51236f82a74
Revises: a13532f366ab
Create Date: 2023-03-05 19:01:03.264159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a51236f82a74'
down_revision = 'a13532f366ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pools_base_name'), 'pools', ['base_name'], unique=False)
    op.create_index(op.f('ix_pools_base_symbol'), 'pools', ['base_symbol'], unique=False)
    op.create_index(op.f('ix_pools_name'), 'pools', ['name'], unique=False)
    op.create_index(op.f('ix_pools_quote_name'), 'pools', ['quote_name'], unique=False)
    op.create_index(op.f('ix_pools_quote_symbol'), 'pools', ['quote_symbol'], unique=False)
    op.create_index(op.f('ix_pools_type'), 'pools', ['type'], unique=False)
    op.add_column('tokens', sa.Column('holders', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('total_supply', sa.Float(), nullable=True))
    op.create_index(op.f('ix_tokens_name'), 'tokens', ['name'], unique=False)
    op.create_index(op.f('ix_tokens_symbol'), 'tokens', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_symbol'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_name'), table_name='tokens')
    op.drop_column('tokens', 'total_supply')
    op.drop_column('tokens', 'holders')
    op.drop_index(op.f('ix_pools_type'), table_name='pools')
    op.drop_index(op.f('ix_pools_quote_symbol'), table_name='pools')
    op.drop_index(op.f('ix_pools_quote_name'), table_name='pools')
    op.drop_index(op.f('ix_pools_name'), table_name='pools')
    op.drop_index(op.f('ix_pools_base_symbol'), table_name='pools')
    op.drop_index(op.f('ix_pools_base_name'), table_name='pools')
    # ### end Alembic commands ###
