"""init

Revision ID: b1ff2a460973
Revises: 
Create Date: 2022-06-04 20:44:38.049920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b1ff2a460973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans_chart',
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_index(op.f('ix_loans_chart_time'), 'loans_chart', ['time'], unique=False)
    op.create_index(op.f('ix_loans_chart_timestamp'), 'loans_chart', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_chart_timestamp'), table_name='loans_chart')
    op.drop_index(op.f('ix_loans_chart_time'), table_name='loans_chart')
    op.drop_table('loans_chart')
    # ### end Alembic commands ###
