
"""v0.4.1-daily-fix

Revision ID: c0be6c7b7b02
Revises: 1caf97846db1
Create Date: 2023-07-30 12:50:39.323791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c0be6c7b7b02'
down_revision = '1caf97846db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_historicals_update_interval', table_name='daily_historicals')
    op.drop_index('ix_daily_historicals_value', table_name='daily_historicals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_historicals_value', 'daily_historicals', ['value'], unique=False)
    op.create_index('ix_daily_historicals_update_interval', 'daily_historicals', ['update_interval'], unique=False)
    # ### end Alembic commands ###
