"""v0.8.0 head nullable fix

Revision ID: ca96155b90c9
Revises: 588a77c865e3
Create Date: 2024-10-29 16:39:01.621973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ca96155b90c9'
down_revision = '588a77c865e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pool_series_15_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pool_series_1_day', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pool_series_1_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pool_series_1_month', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pool_series_1_week', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pool_series_4_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pool_series_5_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('token_series_15_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('token_series_1_day', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('token_series_1_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('token_series_1_month', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('token_series_1_week', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('token_series_4_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('token_series_5_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_series_5_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('token_series_4_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('token_series_1_week', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('token_series_1_month', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('token_series_1_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('token_series_1_day', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('token_series_15_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pool_series_5_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pool_series_4_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pool_series_1_week', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pool_series_1_month', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pool_series_1_hour', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pool_series_1_day', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pool_series_15_min', 'head',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
