"""v0.1.0-change-pool-series-fees

Revision ID: d5b7e25f6165
Revises: dbfc397127cd
Create Date: 2023-03-06 22:29:21.374427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5b7e25f6165'
down_revision = 'dbfc397127cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool_series_15_min', sa.Column('quote_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_15_min', sa.Column('quote_baln_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_15_min', sa.Column('base_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_15_min', sa.Column('base_baln_fees', sa.Float(), nullable=True))
    op.drop_column('pool_series_15_min', 'lp_fees')
    op.drop_column('pool_series_15_min', 'baln_fees')
    op.add_column('pool_series_1_day', sa.Column('quote_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_day', sa.Column('quote_baln_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_day', sa.Column('base_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_day', sa.Column('base_baln_fees', sa.Float(), nullable=True))
    op.drop_column('pool_series_1_day', 'lp_fees')
    op.drop_column('pool_series_1_day', 'baln_fees')
    op.add_column('pool_series_1_hour', sa.Column('quote_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_hour', sa.Column('quote_baln_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_hour', sa.Column('base_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_hour', sa.Column('base_baln_fees', sa.Float(), nullable=True))
    op.drop_column('pool_series_1_hour', 'lp_fees')
    op.drop_column('pool_series_1_hour', 'baln_fees')
    op.add_column('pool_series_1_month', sa.Column('quote_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_month', sa.Column('quote_baln_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_month', sa.Column('base_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_month', sa.Column('base_baln_fees', sa.Float(), nullable=True))
    op.drop_column('pool_series_1_month', 'lp_fees')
    op.drop_column('pool_series_1_month', 'baln_fees')
    op.add_column('pool_series_1_week', sa.Column('quote_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_week', sa.Column('quote_baln_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_week', sa.Column('base_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_1_week', sa.Column('base_baln_fees', sa.Float(), nullable=True))
    op.drop_column('pool_series_1_week', 'lp_fees')
    op.drop_column('pool_series_1_week', 'baln_fees')
    op.add_column('pool_series_4_hour', sa.Column('quote_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_4_hour', sa.Column('quote_baln_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_4_hour', sa.Column('base_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_4_hour', sa.Column('base_baln_fees', sa.Float(), nullable=True))
    op.drop_column('pool_series_4_hour', 'lp_fees')
    op.drop_column('pool_series_4_hour', 'baln_fees')
    op.add_column('pool_series_5_min', sa.Column('quote_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_5_min', sa.Column('quote_baln_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_5_min', sa.Column('base_lp_fees', sa.Float(), nullable=True))
    op.add_column('pool_series_5_min', sa.Column('base_baln_fees', sa.Float(), nullable=True))
    op.drop_column('pool_series_5_min', 'lp_fees')
    op.drop_column('pool_series_5_min', 'baln_fees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool_series_5_min', sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pool_series_5_min', sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pool_series_5_min', 'base_baln_fees')
    op.drop_column('pool_series_5_min', 'base_lp_fees')
    op.drop_column('pool_series_5_min', 'quote_baln_fees')
    op.drop_column('pool_series_5_min', 'quote_lp_fees')
    op.add_column('pool_series_4_hour', sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pool_series_4_hour', sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pool_series_4_hour', 'base_baln_fees')
    op.drop_column('pool_series_4_hour', 'base_lp_fees')
    op.drop_column('pool_series_4_hour', 'quote_baln_fees')
    op.drop_column('pool_series_4_hour', 'quote_lp_fees')
    op.add_column('pool_series_1_week', sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pool_series_1_week', sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pool_series_1_week', 'base_baln_fees')
    op.drop_column('pool_series_1_week', 'base_lp_fees')
    op.drop_column('pool_series_1_week', 'quote_baln_fees')
    op.drop_column('pool_series_1_week', 'quote_lp_fees')
    op.add_column('pool_series_1_month', sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pool_series_1_month', sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pool_series_1_month', 'base_baln_fees')
    op.drop_column('pool_series_1_month', 'base_lp_fees')
    op.drop_column('pool_series_1_month', 'quote_baln_fees')
    op.drop_column('pool_series_1_month', 'quote_lp_fees')
    op.add_column('pool_series_1_hour', sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pool_series_1_hour', sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pool_series_1_hour', 'base_baln_fees')
    op.drop_column('pool_series_1_hour', 'base_lp_fees')
    op.drop_column('pool_series_1_hour', 'quote_baln_fees')
    op.drop_column('pool_series_1_hour', 'quote_lp_fees')
    op.add_column('pool_series_1_day', sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pool_series_1_day', sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pool_series_1_day', 'base_baln_fees')
    op.drop_column('pool_series_1_day', 'base_lp_fees')
    op.drop_column('pool_series_1_day', 'quote_baln_fees')
    op.drop_column('pool_series_1_day', 'quote_lp_fees')
    op.add_column('pool_series_15_min', sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pool_series_15_min', sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pool_series_15_min', 'base_baln_fees')
    op.drop_column('pool_series_15_min', 'base_lp_fees')
    op.drop_column('pool_series_15_min', 'quote_baln_fees')
    op.drop_column('pool_series_15_min', 'quote_lp_fees')
    # ### end Alembic commands ###
