"""v0.1.0-add-stats

Revision ID: dbfc397127cd
Revises: 0de2c7d78956
Create Date: 2023-03-06 20:39:06.675414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'dbfc397127cd'
down_revision = '0de2c7d78956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
