"""add volumes

Revision ID: e812ecf96b8e
Revises: 5871b99d98bf
Create Date: 2022-07-02 23:05:58.986501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e812ecf96b8e'
down_revision = '5871b99d98bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_method_volumes',
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contract_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_timestamp', sa.Integer(), nullable=False),
    sa.Column('end_timestamp', sa.Integer(), nullable=False),
    sa.Column('start_block', sa.Integer(), nullable=False),
    sa.Column('end_block', sa.Integer(), nullable=False),
    sa.Column('update_interval', sa.Integer(), nullable=True),
    sa.Column('days_since_launch', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('num_events', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('address', 'method', 'start_timestamp', 'end_timestamp')
    )
    op.create_index(op.f('ix_contract_method_volumes_contract_name'), 'contract_method_volumes', ['contract_name'], unique=False)
    op.create_index(op.f('ix_contract_method_volumes_days_since_launch'), 'contract_method_volumes', ['days_since_launch'], unique=False)
    op.create_index(op.f('ix_contract_method_volumes_update_interval'), 'contract_method_volumes', ['update_interval'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_method_volumes_update_interval'), table_name='contract_method_volumes')
    op.drop_index(op.f('ix_contract_method_volumes_days_since_launch'), table_name='contract_method_volumes')
    op.drop_index(op.f('ix_contract_method_volumes_contract_name'), table_name='contract_method_volumes')
    op.drop_table('contract_method_volumes')
    # ### end Alembic commands ###
