"""v0.2.3-add-swap-index

Revision ID: ef669e9ed598
Revises: c0be6c7b7b02
Create Date: 2024-02-07 21:53:12.854330

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ef669e9ed598'
down_revision = 'c0be6c7b7b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dex_swaps_pool_id'), 'dex_swaps', ['pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dex_swaps_pool_id'), table_name='dex_swaps')
    # ### end Alembic commands ###
