"""v0.1.0-rebuild-pricing

Revision ID: f2ab3320b375
Revises: 16e92be12b8f
Create Date: 2023-02-28 18:17:23.043767

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2ab3320b375'
down_revision = '16e92be12b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_series_15_min',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('base_volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('lp_fees', sa.Float(), nullable=True),
    sa.Column('baln_fees', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp')
    )
    op.create_table('pool_series_1_day',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('base_volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('lp_fees', sa.Float(), nullable=True),
    sa.Column('baln_fees', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp')
    )
    op.create_table('pool_series_1_hour',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('base_volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('lp_fees', sa.Float(), nullable=True),
    sa.Column('baln_fees', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp')
    )
    op.create_table('pool_series_1_month',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('base_volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('lp_fees', sa.Float(), nullable=True),
    sa.Column('baln_fees', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp')
    )
    op.create_table('pool_series_1_week',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('base_volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('lp_fees', sa.Float(), nullable=True),
    sa.Column('baln_fees', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp')
    )
    op.create_table('pool_series_4_hour',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('base_volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('lp_fees', sa.Float(), nullable=True),
    sa.Column('baln_fees', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp')
    )
    op.create_table('pool_series_5_min',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('base_volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('lp_fees', sa.Float(), nullable=True),
    sa.Column('baln_fees', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp')
    )
    op.create_table('token_series_15_min',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_index(op.f('ix_token_series_15_min_chain_id'), 'token_series_15_min', ['chain_id'], unique=False)
    op.create_index(op.f('ix_token_series_15_min_symbol'), 'token_series_15_min', ['symbol'], unique=False)
    op.create_table('token_series_1_day',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_index(op.f('ix_token_series_1_day_chain_id'), 'token_series_1_day', ['chain_id'], unique=False)
    op.create_index(op.f('ix_token_series_1_day_symbol'), 'token_series_1_day', ['symbol'], unique=False)
    op.create_table('token_series_1_hour',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_index(op.f('ix_token_series_1_hour_chain_id'), 'token_series_1_hour', ['chain_id'], unique=False)
    op.create_index(op.f('ix_token_series_1_hour_symbol'), 'token_series_1_hour', ['symbol'], unique=False)
    op.create_table('token_series_1_month',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_index(op.f('ix_token_series_1_month_chain_id'), 'token_series_1_month', ['chain_id'], unique=False)
    op.create_index(op.f('ix_token_series_1_month_symbol'), 'token_series_1_month', ['symbol'], unique=False)
    op.create_table('token_series_1_week',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_index(op.f('ix_token_series_1_week_chain_id'), 'token_series_1_week', ['chain_id'], unique=False)
    op.create_index(op.f('ix_token_series_1_week_symbol'), 'token_series_1_week', ['symbol'], unique=False)
    op.create_table('token_series_4_hour',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_index(op.f('ix_token_series_4_hour_chain_id'), 'token_series_4_hour', ['chain_id'], unique=False)
    op.create_index(op.f('ix_token_series_4_hour_symbol'), 'token_series_4_hour', ['symbol'], unique=False)
    op.create_table('token_series_5_min',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address', 'timestamp')
    )
    op.create_index(op.f('ix_token_series_5_min_chain_id'), 'token_series_5_min', ['chain_id'], unique=False)
    op.create_index(op.f('ix_token_series_5_min_symbol'), 'token_series_5_min', ['symbol'], unique=False)
    op.drop_table('volume_series_1_week')
    op.drop_table('volume_series_1_day')
    op.drop_table('volume_series_4_hour')
    op.drop_table('volume_series_1_hour')
    op.drop_table('volume_series_15_min')
    op.drop_table('volume_series_5_min')
    op.drop_table('volume_series_1_month')
    op.add_column('pools', sa.Column('price_24h', sa.Float(), nullable=True))
    op.add_column('pools', sa.Column('price_7d', sa.Float(), nullable=True))
    op.add_column('pools', sa.Column('price_30d', sa.Float(), nullable=True))
    op.add_column('pools', sa.Column('price_24h_low', sa.Float(), nullable=True))
    op.add_column('pools', sa.Column('price_24h_high', sa.Float(), nullable=True))
    op.add_column('pools', sa.Column('base_volume_24h', sa.Float(), nullable=True))
    op.add_column('pools', sa.Column('quote_volume_24h', sa.Float(), nullable=True))
    op.add_column('tokens', sa.Column('path', sa.JSON(), nullable=True))
    op.add_column('tokens', sa.Column('pools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'pools')
    op.drop_column('tokens', 'path')
    op.drop_column('pools', 'quote_volume_24h')
    op.drop_column('pools', 'base_volume_24h')
    op.drop_column('pools', 'price_24h_high')
    op.drop_column('pools', 'price_24h_low')
    op.drop_column('pools', 'price_30d')
    op.drop_column('pools', 'price_7d')
    op.drop_column('pools', 'price_24h')
    op.create_table('volume_series_1_month',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp', name='volume_series_1_month_pkey')
    )
    op.create_table('volume_series_5_min',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp', name='volume_series_5_min_pkey')
    )
    op.create_table('volume_series_15_min',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp', name='volume_series_15_min_pkey')
    )
    op.create_table('volume_series_1_hour',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp', name='volume_series_1_hour_pkey')
    )
    op.create_table('volume_series_4_hour',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp', name='volume_series_4_hour_pkey')
    )
    op.create_table('volume_series_1_day',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp', name='volume_series_1_day_pkey')
    )
    op.create_table('volume_series_1_week',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quote_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lp_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baln_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id', 'timestamp', name='volume_series_1_week_pkey')
    )
    op.drop_index(op.f('ix_token_series_5_min_symbol'), table_name='token_series_5_min')
    op.drop_index(op.f('ix_token_series_5_min_chain_id'), table_name='token_series_5_min')
    op.drop_table('token_series_5_min')
    op.drop_index(op.f('ix_token_series_4_hour_symbol'), table_name='token_series_4_hour')
    op.drop_index(op.f('ix_token_series_4_hour_chain_id'), table_name='token_series_4_hour')
    op.drop_table('token_series_4_hour')
    op.drop_index(op.f('ix_token_series_1_week_symbol'), table_name='token_series_1_week')
    op.drop_index(op.f('ix_token_series_1_week_chain_id'), table_name='token_series_1_week')
    op.drop_table('token_series_1_week')
    op.drop_index(op.f('ix_token_series_1_month_symbol'), table_name='token_series_1_month')
    op.drop_index(op.f('ix_token_series_1_month_chain_id'), table_name='token_series_1_month')
    op.drop_table('token_series_1_month')
    op.drop_index(op.f('ix_token_series_1_hour_symbol'), table_name='token_series_1_hour')
    op.drop_index(op.f('ix_token_series_1_hour_chain_id'), table_name='token_series_1_hour')
    op.drop_table('token_series_1_hour')
    op.drop_index(op.f('ix_token_series_1_day_symbol'), table_name='token_series_1_day')
    op.drop_index(op.f('ix_token_series_1_day_chain_id'), table_name='token_series_1_day')
    op.drop_table('token_series_1_day')
    op.drop_index(op.f('ix_token_series_15_min_symbol'), table_name='token_series_15_min')
    op.drop_index(op.f('ix_token_series_15_min_chain_id'), table_name='token_series_15_min')
    op.drop_table('token_series_15_min')
    op.drop_table('pool_series_5_min')
    op.drop_table('pool_series_4_hour')
    op.drop_table('pool_series_1_week')
    op.drop_table('pool_series_1_month')
    op.drop_table('pool_series_1_hour')
    op.drop_table('pool_series_1_day')
    op.drop_table('pool_series_15_min')
    # ### end Alembic commands ###
