"""v0.1.0-add-stats

Revision ID: f6bb95edd03d
Revises: d5b7e25f6165
Create Date: 2023-03-07 16:14:36.540848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f6bb95edd03d'
down_revision = 'd5b7e25f6165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('fees_earned_24h', sa.Float(), nullable=True),
    sa.Column('fees_earned_30d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
